/**
 * Raster Arabic renderer for thermal receipt printing (joined letterforms).
 *
 * Charset mode (ESC t + code page bytes) cannot join Arabic letters — each
 * W1256/PC864 code point is a single isolated glyph. For TRUE joined Arabic
 * we render shaped text into a 1-bit monochrome bitmap and print it with
 * `GS v 0` (raster bit image).
 *
 * Pipeline (matches arabic-encode.ts):
 *   logical Unicode → shapeArabic() → visualOrderForThermal() → blit glyphs
 *
 * Glyphs come from a committed atlas (apps/server/assets/
 * arabic-glyph-atlas.json) generated by scripts/make-arabic-glyph-atlas.mjs
 * (Tajawal, OFL). Zero runtime dependencies: the atlas is plain JSON, no
 * canvas/sharp/harfbuzz. Node 18 safe.
 *
 * Missing glyph fallback: presentation forms that the atlas lacks (e.g. the
 * *isolated* forms Tajawal does not ship) decompose to their base Arabic
 * letter via `presentationFormToBase` — the base glyph IS the isolated shape.
 * Glyphs missing entirely are skipped with zero advance.
 */

import { existsSync, readFileSync } from 'fs';
import { join } from 'path';
import { shapeArabic } from './arabic-shape';
import { visualOrderForThermal } from './arabic-bidi';
import { presentationFormToBase } from './arabic-encode';
import type { MonoBitmap } from './mono-png';
import type { PrinterArabicConfig } from '@spicyhome/shared';

export interface ArabicAtlasGlyph {
  c: number;
  /** Advance width in dots (1 decimal). */
  a: number;
  /** Used bitmap width in dots. */
  w: number;
  /** CELL_H rows; each row is hex, MSB-first, 4 bits per digit. */
  rows: string[];
}

export interface ArabicGlyphAtlas {
  meta: {
    font: string;
    license: string;
    cellHeight: number;
    baseline: number;
    notes?: string;
  };
  glyphs: ArabicAtlasGlyph[];
}

export interface RasterLineOptions {
  /** Max line width in dots. Default 384 (fits 58mm/80mm at 203dpi). */
  maxWidthDots?: number;
  /** Horizontal alignment inside maxWidthDots. Default 'left'. */
  align?: 'left' | 'center';
}

const DEFAULT_MAX_WIDTH_DOTS = 384;

// ── Atlas loading (candidate paths, like thermal-logo.ts) ────────────────────

const ATLAS_FILE = 'arabic-glyph-atlas.json';

let atlasCache: ArabicGlyphAtlas | null | undefined;

/** Candidate absolute paths for the glyph atlas asset. */
export function arabicAtlasCandidates(): string[] {
  const cwd = process.cwd();
  const here = __dirname;
  return [
    // Packaged: cwd = server/
    join(cwd, 'assets', ATLAS_FILE),
    // Packaged: cwd = package root
    join(cwd, 'server', 'assets', ATLAS_FILE),
    // Monorepo root
    join(cwd, 'apps', 'server', 'assets', ATLAS_FILE),
    // Bazel / jest often cwd = apps/server
    join(cwd, 'assets', ATLAS_FILE),
    // Compiled: .../src/modules/printers → apps/server/assets
    join(here, '..', '..', '..', 'assets', ATLAS_FILE),
    // bazel-bin/apps/server/src/modules/printers → apps/server/assets (source tree)
    join(here, '..', '..', '..', '..', 'assets', ATLAS_FILE),
    join(here, '..', '..', '..', '..', '..', 'apps', 'server', 'assets', ATLAS_FILE),
  ];
}

/**
 * Load and parse the glyph atlas. Returns null if missing or invalid.
 * Successful loads are cached for the process lifetime.
 */
export function loadArabicGlyphAtlas(): ArabicGlyphAtlas | null {
  if (atlasCache !== undefined) {
    return atlasCache;
  }

  for (const p of arabicAtlasCandidates()) {
    try {
      if (!existsSync(p)) continue;
      const parsed = JSON.parse(readFileSync(p, 'utf-8')) as ArabicGlyphAtlas;
      if (!parsed.meta || !Array.isArray(parsed.glyphs)) continue;
      atlasCache = parsed;
      return atlasCache;
    } catch {
      // try next candidate
    }
  }

  atlasCache = null;
  return null;
}

/** Test helper — clear the module cache. */
export function clearArabicGlyphAtlasCache(): void {
  atlasCache = undefined;
}

// ── Rendering ────────────────────────────────────────────────────────────────

/**
 * Render a text line that is ALREADY shaped + visually ordered into a
 * monochrome bitmap. Non-Arabic characters are rendered from the ASCII part
 * of the atlas, so mixed lines like "5x شوربة ذرة" work.
 *
 * Returns null when the atlas is unavailable (callers fall back to the
 * charset path).
 */
export function renderArabicLineToMonoBitmap(
  shapedAndOrdered: string,
  opts?: RasterLineOptions,
): MonoBitmap | null {
  const atlas = loadArabicGlyphAtlas();
  if (!atlas) return null;

  const cellHeight = atlas.meta.cellHeight;
  const maxWidth = Math.max(1, opts?.maxWidthDots ?? DEFAULT_MAX_WIDTH_DOTS);
  const glyphsByCp = new Map<number, ArabicAtlasGlyph>();
  for (const g of atlas.glyphs) glyphsByCp.set(g.c, g);

  // Layout pass: compute ink width so we can honor alignment.
  const layout = layoutLine(shapedAndOrdered, glyphsByCp);
  const contentWidth = Math.min(layout.width, maxWidth);
  const align = opts?.align ?? 'left';
  const offset = align === 'center' ? Math.floor((maxWidth - contentWidth) / 2) : 0;

  // Second pass: blit glyphs into the bitmap.
  const width = maxWidth;
  const bits = new Uint8Array(width * cellHeight);
  let x = offset;
  for (const ch of shapedAndOrdered) {
    const cp = ch.codePointAt(0) as number;
    const glyph = lookupGlyph(cp, glyphsByCp);
    if (!glyph) continue; // unmapped — skip with zero advance
    const gx = Math.round(x);
    if (gx >= width) break; // line full
    blitGlyph(glyph, gx, bits, width, cellHeight);
    x += glyph.a;
  }

  return { width, height: cellHeight, bits };
}

/**
 * Shape + visually order + rasterize a LOGICAL Unicode line in one call —
 * convenience for the receipt builder.
 */
export function renderArabicLineFromLogical(
  logical: string,
  config: PrinterArabicConfig,
  opts?: RasterLineOptions,
): MonoBitmap | null {
  const shaped = shapeArabic(logical);
  const ordered = visualOrderForThermal(shaped, config.visualRtl);
  return renderArabicLineToMonoBitmap(ordered, opts);
}

// ── Internals ────────────────────────────────────────────────────────────────

interface Layout {
  width: number;
  count: number;
}

function layoutLine(text: string, glyphsByCp: Map<number, ArabicAtlasGlyph>): Layout {
  let width = 0;
  let count = 0;
  for (const ch of text) {
    const cp = ch.codePointAt(0) as number;
    const glyph = lookupGlyph(cp, glyphsByCp);
    if (!glyph) continue;
    width += glyph.a;
    count++;
  }
  return { width, count };
}

/**
 * Resolve a glyph for a code point, falling back to the base Arabic letter
 * for presentation forms the atlas does not cover.
 */
function lookupGlyph(
  cp: number,
  glyphsByCp: Map<number, ArabicAtlasGlyph>,
): ArabicAtlasGlyph | null {
  let glyph = glyphsByCp.get(cp);
  if (glyph && (glyph.a > 0 || glyph.w > 0)) return glyph;
  if (glyph && glyph.w === 0 && glyph.a === 0) {
    // Empty atlas entry — try the base-letter fallback for presentation forms.
    const base = presentationFormToBase(cp);
    if (base !== cp) {
      glyph = glyphsByCp.get(base);
      if (glyph && (glyph.a > 0 || glyph.w > 0)) return glyph;
    }
    return null;
  }
  return null;
}

/** Blit one glyph at pixel x0 (bitmap row-major, 1 = ink). */
function blitGlyph(
  glyph: ArabicAtlasGlyph,
  x0: number,
  bits: Uint8Array,
  width: number,
  cellHeight: number,
): void {
  if (glyph.w <= 0 || glyph.rows.length === 0) return;
  const nRows = Math.min(cellHeight, glyph.rows.length);
  for (let y = 0; y < nRows; y++) {
    const row = glyph.rows[y];
    if (!row) continue;
    for (let x = 0; x < glyph.w; x++) {
      const dx = x0 + x;
      if (dx >= width) break;
      const digit = row[Math.floor(x / 4)];
      if (digit === undefined) continue;
      const bit = (parseInt(digit, 16) >> (3 - (x % 4))) & 1;
      if (bit) bits[y * width + dx] = 1;
    }
  }
}
