/**
 * bake/emit — Unit Tests
 *
 * - buildEmitScriptSource: embedded base64 payload round-trip (label/sourceId/
 *   format/printer fields), format + regenerate command in the header, Node 18
 *   source style (no optional chaining / template literals in generated code)
 * - writeEmitScript: writes the source, creating parent directories on demand
 */
import { mkdtempSync, readFileSync } from 'fs';
import { tmpdir } from 'os';
import { join } from 'path';
import { buildEmitScriptSource, writeEmitScript } from './emit';
import type { BakedPrintJob } from './types';

/** A minimal kitchen-style job with a distinctive buffer. */
function makeJob(overrides: Partial<BakedPrintJob> = {}): BakedPrintJob {
  return {
    format: 'kitchen',
    label: 'INV26-0001',
    sourceId: 7,
    printer: {
      printerId: 1,
      printerName: 'Kitchen A',
      connectionType: 'tcp',
      ip: '192.168.1.51',
      port: 9100,
      windowsPrinterName: null,
    },
    buffer: Buffer.from([0x1b, 0x40, 0x48, 0x65, 0x6c, 0x6c, 0x6f]),
    ...overrides,
  };
}

interface EmbeddedJob {
  label: string;
  sourceId: number;
  format: string;
  bufferB64: string;
  printer: {
    printerId: number;
    printerName: string;
    connectionType: string;
    ip: string;
    port: number;
    windowsPrinterName: string | null;
  };
}

/** Extract the JSON payload embedded in a generated emit script. */
function extractPayload(source: string): EmbeddedJob[] {
  const match = source.match(/JSON\.parse\('((?:[^'\\]|\\.)*)'\)/);
  expect(match).not.toBeNull();
  const decoded = match![1].replace(/\\'/g, "'").replace(/\\\\/g, '\\');
  return JSON.parse(decoded) as EmbeddedJob[];
}

describe('buildEmitScriptSource', () => {
  it('embeds base64 buffers + printer targets and round-trips the payload', () => {
    const jobs = [
      makeJob(),
      makeJob({
        label: 'Order-1003',
        sourceId: 9,
        printer: {
          printerId: 2,
          printerName: 'Kitchen B',
          connectionType: 'windows',
          ip: '',
          port: 9100,
          windowsPrinterName: 'Epson Kitchen B',
        },
      }),
    ];
    const source = buildEmitScriptSource(jobs, 'kitchen');

    const payload = extractPayload(source);
    expect(payload).toHaveLength(2);

    // Field mapping: label/sourceId/format instead of documentId/orderId.
    expect(payload[0].label).toBe('INV26-0001');
    expect(payload[0].sourceId).toBe(7);
    expect(payload[0].format).toBe('kitchen');
    expect(payload[1].label).toBe('Order-1003');
    expect(payload[1].sourceId).toBe(9);
    expect(payload[1].format).toBe('kitchen');

    for (let i = 0; i < payload.length; i++) {
      expect(Buffer.from(payload[i].bufferB64, 'base64').equals(jobs[i].buffer)).toBe(true);
    }

    // Printer target passthrough (tcp + windows bits).
    expect(payload[0].printer).toEqual({
      printerId: 1,
      printerName: 'Kitchen A',
      connectionType: 'tcp',
      ip: '192.168.1.51',
      port: 9100,
      windowsPrinterName: null,
    });
    expect(payload[1].printer.windowsPrinterName).toBe('Epson Kitchen B');
    expect(payload[1].printer.connectionType).toBe('windows');

    // Plan logs reference job.label, not documentId.
    expect(source).toContain('job.label');
  });

  it('names the format + regenerate command + default out path in the header', () => {
    const source = buildEmitScriptSource([makeJob()], 'kitchen');
    expect(source).toContain('Generated by bake-print-probe');
    expect(source).toMatch(/Generated at: \d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d{3}Z/);
    // Same stamp at EOF for copy-paste / tail checks
    expect(source.trimEnd()).toMatch(
      /\/\/ Generated at: \d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d{3}Z$/,
    );
    expect(source).toContain('bazel run //apps/server:bake_print_probe -- --format kitchen');
    expect(source).toContain('tmp/print-probe/send-kitchen.js');
    expect(source).toContain("const BAKE_FORMAT = 'kitchen';");
    expect(source).toContain("Baked 1 job(s) for format 'kitchen'.");
    expect(source).toContain('PAPER STORM WARNING');
    expect(source).toContain('Requires Node 18');
    expect(source).toContain("require('net')");
    expect(source).toContain('192.168.1.51'); // tcp target ip
    expect(source).toContain('9100'); // tcp target port
    expect(source).toContain('INV26-0001'); // label in plan log
  });

  it('generated code stays Node 18 / ES5-ish: no optional chaining or template literals', () => {
    const jobs = [
      makeJob(),
      makeJob({
        printer: {
          printerId: 2,
          printerName: 'Kitchen B',
          connectionType: 'windows',
          ip: '',
          port: 9100,
          windowsPrinterName: 'Epson Kitchen B',
        },
      }),
    ];
    const source = buildEmitScriptSource(jobs, 'kitchen');

    expect(source).not.toContain('?.');
    expect(source).not.toContain('`');
    // Windows fallback + temp bin prefix survive the port.
    expect(source).toContain("printer.windowsPrinterName || 'windows queue'");
    expect(source).toContain("'send-print-probe-' + Date.now()");
    // Log prefix uses send-<format>.
    expect(source).toContain("'send-' + BAKE_FORMAT + ': '");
  });

  it('is parseable as plain JavaScript without executing the print path', () => {
    const source = buildEmitScriptSource([makeJob()], 'kitchen');
    expect(() => {
      new Function(source);
    }).not.toThrow();
  });
});

describe('writeEmitScript', () => {
  it('writes the source, creating parent directories on demand', () => {
    const dir = mkdtempSync(join(tmpdir(), 'bake-emit-'));
    const out = join(dir, 'nested', 'out', 'send-kitchen.js');
    const source = buildEmitScriptSource([makeJob()], 'kitchen');
    writeEmitScript(out, source);
    expect(readFileSync(out, 'utf8')).toBe(source);
  });
});
