/**
 * bake/emit.ts — generate the self-contained Node 18 emit script.
 *
 * Ported and generalized from the KOT-only baker: given the collected jobs and
 * the probe format, build the full source of a plain CommonJS script that
 * prints every baked buffer immediately when run on the live Win7 POS machine
 * (TCP raw socket or win_rawprint.exe spooler). No TypeScript, no server
 * modules, only Node builtins.
 */

import { mkdirSync, writeFileSync } from 'fs';
import { dirname } from 'path';
import type { BakedPrintJob, ProbeFormat } from './types';

/**
 * Build the full source of the Node 18-compatible emit script.
 *
 * The script prints immediately when run: every baked buffer is sent to its
 * printer. It is plain CommonJS with only Node builtins — no TypeScript, no
 * server modules. Generated code stays Node 18 / ES5-ish (var/function, string
 * concatenation, no optional chaining, no template literals) so it runs on the
 * bundled portable Node 18 and is trivially greppable.
 */
export function buildEmitScriptSource(jobs: BakedPrintJob[], format: ProbeFormat): string {
  const payload = jobs.map((job) => ({
    label: job.label,
    sourceId: job.sourceId,
    format: job.format,
    printer: {
      printerId: job.printer.printerId,
      printerName: job.printer.printerName,
      connectionType: job.printer.connectionType,
      ip: job.printer.ip,
      port: job.printer.port,
      windowsPrinterName: job.printer.windowsPrinterName,
    },
    bufferB64: job.buffer.toString('base64'),
  }));

  // Embed as JSON.parse('<escaped json>') so tests can round-trip the payload
  // and so the script never needs `require('./jobs.json')` at runtime.
  const jsonLiteral = JSON.stringify(payload).replace(/\\/g, '\\\\').replace(/'/g, "\\'");
  const generatedAt = new Date().toISOString();

  return `/**
  * Generated by bake-print-probe (apps/server/src/modules/printers/bake/emit.ts).
  * Generated at: ${generatedAt}
  * Do not edit by hand — regenerate with: bazel run //apps/server:bake_print_probe -- --format ${format}
  *
  * Default out path: tmp/print-probe/send-${format}.js
  *
  * Requires Node 18+ (runs on the Win7 POS machine with the bundled portable
  * Node 18). Single file, no dependencies beyond Node builtins
  * (net, fs, path, os, child_process).
  *
  * Baked ${jobs.length} job(s) for format '${format}'.
  *
 * !!! PAPER STORM WARNING !!!
 * Running this script IMMEDIATELY prints every baked job to the real
 * printers. There is no dry-run. Do not run during service, and tell the
 * kitchen before a probe run.
 *
 * Exit code: 0 when every job printed; 1 when one or more jobs failed
 * (printing continues past failures — a dead printer must not stop the other
 * jobs); 2 defensively when the payload is empty (the baker never writes
 * an empty script).
 */
'use strict';

const net = require('net');
const fs = require('fs');
const path = require('path');
const os = require('os');
const { spawn } = require('child_process');

const BAKE_FORMAT = '${format}';

// Baked payload: one entry per (source x target printer).
const BAKED_JOBS = JSON.parse('${jsonLiteral}');

/**
 * Resolve win_rawprint.exe with the same rules as the production server
 * (win-rawprint-helpers.ts): WIN_RAWPRINT_PATH env, cwd, cwd/bin/,
 * cwd/prebuilt/, then next to process.execPath. Returns the full path or null.
 */
function resolveWinRawprintPath() {
  const envPath = process.env.WIN_RAWPRINT_PATH;
  if (envPath && fs.existsSync(envPath)) return envPath;

  const relCandidates = [
    'win_rawprint.exe',
    path.join('bin', 'win_rawprint.exe'),
    path.join('prebuilt', 'win_rawprint.exe'),
  ];

  const cwd = process.cwd();
  for (let i = 0; i < relCandidates.length; i++) {
    const full = path.join(cwd, relCandidates[i]);
    if (fs.existsSync(full)) return full;
  }

  const execDir = path.dirname(process.execPath);
  for (let i = 0; i < relCandidates.length; i++) {
    const full = path.join(execDir, relCandidates[i]);
    if (fs.existsSync(full)) return full;
  }

  return null;
}

/** Human-readable target for logs: "192.168.1.51:9100" or the queue name. */
function describeTarget(printer) {
  if (printer.connectionType === 'windows') {
    return printer.windowsPrinterName || 'windows queue';
  }
  return printer.ip + ':' + printer.port;
}

/**
 * Send one baked buffer to a TCP raw printer (:9100). Resolves when the
 * socket closed cleanly; rejects on error/timeout.
 */
function printTcp(job, timeoutMs) {
  return new Promise(function (resolvePromise, rejectPromise) {
    const socket = new net.Socket();
    let timer = null;
    let settled = false;

    function fail(err) {
      if (settled) return;
      settled = true;
      if (timer) clearTimeout(timer);
      socket.destroy();
      rejectPromise(err);
    }

    timer = setTimeout(function () {
      fail(new Error('TCP timeout after ' + timeoutMs + 'ms'));
    }, timeoutMs);

    socket.once('error', fail);
    socket.once('close', function () {
      if (settled) return;
      settled = true;
      if (timer) clearTimeout(timer);
      resolvePromise();
    });

    socket.connect(job.printer.port, job.printer.ip, function () {
      socket.write(job.buffer);
      socket.end();
    });
  });
}

/**
 * Send one baked buffer to a Windows spooler queue via win_rawprint.exe:
 * write a temp .bin, spawn the exe with the queue name + path, await exit,
 * remove the temp file. win32 only — the Windows spooler cannot be driven
 * from another OS.
 */
function printWindows(job, timeoutMs) {
  return new Promise(function (resolvePromise, rejectPromise) {
    if (process.platform !== 'win32') {
      rejectPromise(new Error('windows connection target requires running on win32'));
      return;
    }
    if (!job.printer.windowsPrinterName) {
      rejectPromise(new Error('windows connection target is missing windowsPrinterName'));
      return;
    }
    const exe = resolveWinRawprintPath();
    if (!exe) {
      rejectPromise(
        new Error(
          'win_rawprint.exe not found — set WIN_RAWPRINT_PATH or place it next to ' +
            'this script, in bin/, or in prebuilt/',
        ),
      );
      return;
    }

    const tmpFile = path.join(
      os.tmpdir(),
      'send-print-probe-' + Date.now() + '-' + Math.random().toString(36).slice(2) + '.bin',
    );

    fs.writeFile(tmpFile, job.buffer, function (writeErr) {
      if (writeErr) {
        rejectPromise(writeErr);
        return;
      }
      const child = spawn(exe, [job.printer.windowsPrinterName, tmpFile], {
        windowsHide: true,
        stdio: ['ignore', 'pipe', 'pipe'],
      });
      let stderr = '';
      let settled = false;

      const timer = setTimeout(function () {
        if (settled) return;
        settled = true;
        child.kill();
        fs.unlink(tmpFile, function () {});
        rejectPromise(new Error('win_rawprint.exe timed out after ' + timeoutMs + 'ms'));
      }, timeoutMs);

      child.stderr.on('data', function (chunk) {
        stderr += chunk.toString();
      });

      child.on('error', function (err) {
        if (settled) return;
        settled = true;
        clearTimeout(timer);
        fs.unlink(tmpFile, function () {});
        rejectPromise(new Error('win_rawprint.exe spawn failed: ' + err.message));
      });

      child.on('close', function (code) {
        fs.unlink(tmpFile, function () {});
        if (settled) return;
        settled = true;
        clearTimeout(timer);
        if (code === 0) {
          resolvePromise();
          return;
        }
        rejectPromise(
          new Error('win_rawprint.exe exited with ' + (stderr.trim() || String(code))),
        );
      });
    });
  });
}

async function main() {
  // Decode baked buffers once, up front.
  for (let i = 0; i < BAKED_JOBS.length; i++) {
    BAKED_JOBS[i].buffer = Buffer.from(BAKED_JOBS[i].bufferB64, 'base64');
  }

  console.log('send-' + BAKE_FORMAT + ': ' + BAKED_JOBS.length + ' baked job(s)');
  console.log('Plan:');
  for (let i = 0; i < BAKED_JOBS.length; i++) {
    const job = BAKED_JOBS[i];
    console.log(
      '  ' +
        (i + 1) +
        '. ' +
        job.label +
        ' -> ' +
        job.printer.printerName +
        ' (' +
        job.printer.connectionType +
        ' ' +
        describeTarget(job.printer) +
        ')',
    );
  }

  if (BAKED_JOBS.length === 0) {
    // Defensive: the baker never writes an empty script, but if the payload
    // was gutted in transit we must not silently print nothing successfully.
    console.error('No baked jobs found — nothing to print.');
    process.exitCode = 2;
    return;
  }

  // Print sequentially; keep going when a job fails. Exit non-zero at the end
  // if anything failed, so the caller knows the probe was incomplete.
  let failures = 0;
  for (let i = 0; i < BAKED_JOBS.length; i++) {
    const job = BAKED_JOBS[i];
    const target = describeTarget(job.printer);
    try {
      if (job.printer.connectionType === 'windows') {
        await printWindows(job, 15000);
      } else {
        await printTcp(job, 5000);
      }
      console.log('OK   ' + job.label + ' -> ' + job.printer.printerName + ' (' + target + ')');
    } catch (err) {
      failures++;
      console.error(
        'FAIL ' +
          job.label +
          ' -> ' +
          job.printer.printerName +
          ' (' +
          target +
          '): ' +
          (err && err.message ? err.message : String(err)),
      );
    }
  }

  if (failures > 0) {
    console.error(failures + ' of ' + BAKED_JOBS.length + ' job(s) failed.');
    process.exitCode = 1;
  } else {
    console.log('All ' + BAKED_JOBS.length + ' baked job(s) printed.');
  }
}

if (typeof require !== 'undefined' && require.main === module) {
  main().catch(function (err) {
    console.error(
      'send-' + BAKE_FORMAT + ' failed:',
      err && err.message ? err.message : String(err),
    );
    process.exitCode = 1;
  });
}

// Generated at: ${generatedAt}
`;
}

// ── Write ────────────────────────────────────────────────────────────────────

/**
 * Write the emit script to disk, creating parent directories on demand.
 * Callers must only call this when `jobs.length > 0` — an empty script must
 * never overwrite a previous good one (empty bake = loud failure).
 */
export function writeEmitScript(outPath: string, source: string): void {
  mkdirSync(dirname(outPath), { recursive: true });
  writeFileSync(outPath, source, 'utf8');
}
