#!/usr/bin/env bash
# Allocate stable per-worktree ports + DB path and write .env.worktree.
#
# Does not create git worktrees. Prefer scripts/worktree/bootstrap.sh for a
# full cold-checkout bootstrap (env + Node check + pnpm install).
#
# Main worktree (directory .git): defaults PORT=3742, VITE_PORT=6124.
# Linked worktrees: hash(realpath) → offset 1..999 so ports never collide
# with main and stay stable across restarts.
#
# Usage:
#   scripts/worktree/env.sh              # write .env.worktree in cwd/repo root
#   scripts/worktree/env.sh --print      # print env without writing
#   scripts/worktree/env.sh --force      # overwrite existing .env.worktree
#   scripts/worktree/env.sh /path/to/wt  # target another checkout

set -euo pipefail

PRINT_ONLY=false
FORCE=false
TARGET=""

while [[ $# -gt 0 ]]; do
  case "$1" in
    --print) PRINT_ONLY=true; shift ;;
    --force) FORCE=true; shift ;;
    -h|--help)
      sed -n '2,14p' "$0" | sed 's/^# \?//'
      exit 0
      ;;
    *)
      if [[ -n "$TARGET" ]]; then
        echo "Error: unexpected argument: $1" >&2
        exit 1
      fi
      TARGET="$1"
      shift
      ;;
  esac
done

if [[ -n "$TARGET" ]]; then
  ROOT="$(cd "$TARGET" && pwd)"
else
  # Prefer git toplevel when inside a worktree; else script-relative repo root.
  if ROOT="$(git -C "${PWD}" rev-parse --show-toplevel 2>/dev/null)"; then
    :
  else
    ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
  fi
fi

cd "$ROOT"

slug_from_branch() {
  local branch
  branch="$(git rev-parse --abbrev-ref HEAD 2>/dev/null || echo worktree)"
  if [[ "$branch" == "HEAD" ]]; then
    branch="$(git rev-parse --short HEAD 2>/dev/null || echo detached)"
  fi
  # filesystem-safe slug
  echo "$branch" | tr '[:upper:]' '[:lower:]' | sed -E 's/[^a-z0-9]+/-/g; s/^-+//; s/-+$//; s/-+/-/g'
}

# Stable 32-bit-ish hash → 1..999 (never 0 — reserved for main defaults).
path_offset() {
  local path="$1"
  local h
  h="$(printf '%s' "$path" | cksum | awk '{print $1}')"
  echo $(( (h % 999) + 1 ))
}

SLUG="$(slug_from_branch)"
IS_MAIN=false
if [[ -d "$ROOT/.git" ]]; then
  IS_MAIN=true
fi

if $IS_MAIN; then
  PORT=3742
  VITE_PORT=6124
  INSPECT_PORT=9229
  SPICYHOME_DB="$ROOT/data/spicyhome.db"
  WORKTREE_KIND=main
  OFFSET=0
else
  OFFSET="$(path_offset "$ROOT")"
  PORT=$((3742 + OFFSET))
  VITE_PORT=$((6124 + OFFSET))
  INSPECT_PORT=$((9229 + OFFSET))
  SPICYHOME_DB="$ROOT/data/spicyhome-${SLUG}.db"
  WORKTREE_KIND=linked
fi

ENV_FILE="$ROOT/.env.worktree"

render() {
  cat <<EOF
# Generated by scripts/worktree/env.sh — do not commit.
# kind=${WORKTREE_KIND} slug=${SLUG} offset=${OFFSET}
PORT=${PORT}
VITE_PORT=${VITE_PORT}
INSPECT_PORT=${INSPECT_PORT}
SPICYHOME_DB=${SPICYHOME_DB}
WORKTREE_SLUG=${SLUG}
TZ=Asia/Riyadh
EOF
}

if $PRINT_ONLY; then
  render
  exit 0
fi

if [[ -f "$ENV_FILE" ]] && ! $FORCE; then
  echo "Exists: $ENV_FILE (use --force to overwrite)"
  # shellcheck disable=SC1090
  set -a
  # shellcheck source=/dev/null
  source "$ENV_FILE"
  set +a
  echo "  PORT=${PORT:-?}  VITE_PORT=${VITE_PORT:-?}  DB=${SPICYHOME_DB:-?}"
  exit 0
fi

mkdir -p "$ROOT/data"
render >"$ENV_FILE"
echo "Wrote $ENV_FILE"
echo "  kind=${WORKTREE_KIND}  slug=${SLUG}  offset=${OFFSET}"
echo "  server  http://localhost:${PORT}"
echo "  pos     http://localhost:${VITE_PORT}"
echo "  inspect ${INSPECT_PORT}"
echo "  db      ${SPICYHOME_DB}"
